# StarPU --- Runtime system for heterogeneous multicore architectures.
# -*- coding: utf-8 -*-
#
# Copyright (C) 2010-2025  Université de Bordeaux, CNRS (LaBRI UMR 5800), Inria
#
# StarPU is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or (at
# your option) any later version.
#
# StarPU is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU Lesser General Public License in COPYING.LGPL for more details.
#

config = {
    'opts'        : [ '--disable-static', '--disable-build-doc', '--enable-debug', '--enable-starpupy', '--enable-hdf5'],
    'env'         : {'STARPU_SILENT' : '1',
                     'STARPU_SSILENT' : '1',
                     'SOCL_OCL_LIB_OPENCL' : '/usr/lib/x86_64-linux-gnu/libOpenCL.so',
                     'MALLOC_PERTURB_' : '1234',
                     'OPENBLAS_NUM_THREADS': '1'
                    },
}

profiles = [
# Compilation profiles
    { 'name'        : 'compilation-disable-cuda-disable-hip-disable-opencl',
      'opts'        : [ '--disable-gdb', '--disable-cuda', '--disable-hip', '--disable-opencl' ],
      'deploy'      : False,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'compilation-disable-cuda-enable-hip-disable-opencl',
      'opts'        : [ '--disable-gdb', '--disable-cuda', '--enable-hip', '--disable-opencl' ],
      'deploy'      : False,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'compilation-enable-cuda-disable-hip-disable-opencl',
      'opts'        : [ '--disable-gdb', '--enable-cuda', '--disable-hip', '--disable-opencl' ],
      'deploy'      : False,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'compilation-enable-cuda-enable-hip-disable-opencl',
      'opts'        : [ '--disable-gdb', '--enable-cuda', '--enable-hip', '--disable-opencl' ],
      'deploy'      : False,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'compilation-disable-cuda-disable-hip-enable-opencl',
      'opts'        : [ '--disable-gdb', '--disable-cuda', '--disable-hip', '--enable-opencl' ],
      'deploy'      : False,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'compilation-disable-cuda-enable-hip-enable-opencl',
      'opts'        : [ '--disable-gdb', '--disable-cuda', '--enable-hip', '--enable-opencl' ],
      'deploy'      : False,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'compilation-scan',
      'opts'        : [],
      'env'         : { 'CXXFLAGS' : '-std=c++11' },
      'deploy'      : False,
      'scan'        : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'compilation-windows-i686',
      'opts'        : ['--disable-gdb', '--host=i686-w64-mingw32', '--without-mpicc', '--without-x', '--without-hwloc', '--disable-starpufft', '--disable-hdf5', '--disable-fortran', '--disable-starpupy'],
      'env'         : { 'PKG_CONFIG_LIBDIR' : '/usr/i686-w64-mingw32/lib/pkgconfig' },
      'deploy'      : False,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'compilation-windows-x86-64',
      'opts'        : ['--disable-gdb', '--host=x86_64-w64-mingw32', '--without-mpicc', '--without-x', '--without-hwloc', '--disable-starpufft', '--disable-hdf5', '--disable-fortran', '--disable-starpupy'],
      'env'         : { 'PKG_CONFIG_LIBDIR' : '/usr/x86_64-w64-mingw32/lib/pkgconfig' },
      'deploy'      : False,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'compilation-windows',
      'opts'        : ['--disable-gdb', '--host=i586-mingw32msvc', '--without-mpicc', '--without-x', '--without-hwloc', '--disable-starpufft', '--disable-hdf5', '--disable-fortran', '--disable-starpupy'],
      'env'         : { 'PKG_CONFIG_LIBDIR' : '/usr/i586-mingw32msvc/lib/pkgconfig' },
      'deploy'      : False,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'compilation-leveldb',
      'opts'        : [ '--disable-gdb', '--enable-leveldb' ],
      'env'         : { 'CXX' : '/usr/bin/g++-9' }, # g++ < 5.x seems to generate incorrect name mangling for leveldb::DB::Open
      'deploy'      : False,
      'hosts'       : ['node_gpu']
    },

    # Benchmarks and coverage
    { 'name'        : 'benchmarks',
      'global_opts' : False,
      'opts'        : ['--without-mpiexec', '--disable-debug', '--enable-maxcpus=128'],
      'deploy'      : True,
      'bench'       : True,
      'rcheck'      : ['-C', 'tests/microbenchs'],
      'hosts'       : ['node_release']
    },
    { 'name'        : 'coverage',
      'release'     : True,
      'deploy'      : True,
      'coverage'    : ['--enable-coverage'],
      'opts'        : ['--enable-build-doc', '--enable-build-doc-pdf'],
      'hosts'       : ['node_release'],
      'ignore_fail' : True
    },

    # Execution profiles
    { 'name'        : 'default',
      'deploy'      : True,
      'global_opts' : False,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'default-nogpu',
      'deploy'      : True,
      'global_opts' : False,
      'opts'        : ['--without-mpiexec', '--disable-debug', '--enable-maxcpus=128'],
      'env'         : { 'STARPU_TIMEOUT_ENV' : '25000' },
      'hosts'       : ['node_nogpu'],
    },
    { 'name'        : 'mpi-ms',
      'deploy'      : True,
      'opts'        : ['--enable-mpi-server-client', '--disable-socl', '--disable-cpu', '--disable-cuda', '--disable-hip', '--disable-opencl'],
      'hosts'       : ['node_nogpu'],
      'env'         : {'STARPU_MICROBENCHS_DISABLED' : '1'},
    },
    { 'name'        : 'mpi-ms-thread',
      'deploy'      : True,
      'opts'        : ['--enable-mpi-server-client', '--disable-socl', '--disable-cpu', '--disable-cuda', '--disable-hip', '--disable-opencl'],
      'env'         : { 'STARPU_MPI_MS_MULTIPLE_THREAD' : '1' },
      'hosts'       : ['node_nogpu'],
      'env'         : {'STARPU_MICROBENCHS_DISABLED' : '1'},
    },
    { 'name'        : 'tcpip-ms',
      'deploy'      : True,
      'opts'        : ['--enable-tcpip-server-client', '--disable-socl', '--disable-cpu', '--disable-cuda', '--disable-hip', '--disable-opencl', '--disable-mpi-check', '--disable-starpu-openmp', '--disable-starpu-openmp'],
      'hosts'       : ['node_nogpu'],
      'env'         : {'STARPU_MICROBENCHS_DISABLED' : '1'},
    },
    { 'name'        : 'tcpip-ms-thread',
      'deploy'      : True,
      'opts'        : ['--enable-tcpip-server-client', '--disable-socl', '--disable-cpu', '--disable-cuda', '--disable-hip', '--disable-opencl', '--disable-mpi-check', '--disable-starpu-openmp'],
      'env'         : { 'STARPU_TCPIP_MS_MULTIPLE_THREAD' : '1' },
      'hosts'       : ['node_nogpu'],
      'env'         : {'STARPU_MICROBENCHS_DISABLED' : '1'},
    },
    { 'name'        : 'numa',
      'deploy'      : True,
      'env'         : { 'STARPU_USE_NUMA' : '1' },
      'opts'        : ['--enable-mpi-check'],
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'mpi-nocache',
      'deploy'      : True,
      'opts'        : {'--enable-mpi-check'},
      'rcheck'      : ['-C', 'mpi'],
      'env'         : { 'STARPU_MPI_CACHE' : '0' },
      'hosts'       : ['node_gpu'],
    },
    { 'name'        : 'nmad',
      'deploy'      : True,
      'opts'        : ['--enable-nmad', '--enable-mpi-check', '--disable-cuda', '--disable-hip', '--disable-opencl'],
      'rcheck'      : ['-C', 'mpi'],
      'env'         : {'PATH' : '${HOME}/softs/starpu/pm2/install/master/bin:${PATH}',
                       'LD_LIBRARY_PATH' : '${HOME}/softs/starpu/pm2/install/master/lib:${LD_LIBRARY_PATH}',
                       'PKG_CONFIG_PATH' : '${HOME}/softs/starpu/pm2/install/master/lib/pkgconfig:${PKG_CONFIG_PATH}'},
      'prologue'    : ['/home/benchmarks/buildbot/master/starpu/scripts/updatePm2.sh', 'pukabi+madmpi.conf'],
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'enable-fast',
      'opts'        : ['--enable-fast', '--disable-full-gdb-information'],
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'enable-spinlock-check',
      'opts'        : ['--enable-spinlock-check'],
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'disable-opencl',
      'opts'        : ['--disable-opencl'],
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'disable-hip',
      'opts'        : ['--disable-hip'],
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'disable-cuda',
      'opts'        : ['--disable-cuda'],
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'disable-cpu',
      'deploy'      : True,
      'opts'        : ['--disable-cpu'],
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'limit-cpu',
      'deploy'      : True,
      'opts'        : ['--enable-maxcpus=8'],
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'cuda-opencl',
      'opts'        : ['--enable-cuda', '--enable-opencl', '--enable-maxcudadev=2', '--enable-mpi-minimal-tests'],
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'cuda-opencl-runtime',
      'opts'        : ['--enable-cuda', '--enable-opencl', '--enable-mpi-minimal-tests'],
      'deploy'      : True,
      'env'         : { 'STARPU_NCUDA' : '2' },
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'cuda-cudaid',
      'opts'        : ['--enable-cuda', '--enable-mpi-minimal-tests'],
      'deploy'      : True,
      'env'         : { 'STARPU_NCUDA' : '2', 'STARPU_WORKERS_CUDAID' : '1 2' },
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'opencl-only',
      'opts'        : ['--disable-cpu', '--disable-cuda', '--disable-hip', '--enable-opencl', '--enable-mpi-minimal-tests'],
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'hip-only',
      'opts'        : ['--disable-cpu', '--disable-cuda', '--disable-opencl', '--enable-hip', '--enable-mpi-minimal-tests'],
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'maxnodes-1',
      'opts'        : ['--enable-maxnodes=1', '--disable-cuda', '--disable-hip', '--disable-opencl'],
      'env'         : { 'STARPU_USE_NUMA' : '0' },
      'deploy'      : True,
      'hosts'       : ['node_nogpu'],
    },
    { 'name'        : 'debug-verbose',
      'opts'        : ['--enable-verbose'],
      'env'         : { 'STARPU_LOGFILENAME' : '/tmp/starpu_run.log' },
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'profiling',
      'deploy'      : True,
      'env'         : { 'STARPU_PROFILING' : '1', 'STARPU_PROF_PAPI_EVENTS' : 'PAPI_TOT_INS PAPI_TOT_CYC' },
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'without-hwloc',
      'opts'        : ['--without-hwloc'],
      'deploy'      : True,
      'env'         : { 'STARPU_NCPUS' : '2', 'STARPU_WORKERS_NOBIND' : '1'},
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'memory-stats',
      'opts'        : ['--enable-memory-stats'],
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'disable-allocation-cache',
      'opts'        : ['--disable-allocation-cache'],
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'blas',
      'opts'        : ['--enable-blas-lib=atlas'],
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'noblas',
      'opts'        : ['--enable-blas-lib=none'],
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'ncuda-nopencl-zero',
      'env'         : { 'STARPU_NCUDA' : '0', 'STARPU_NOPENCL' : '0' },
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'cuda0',
      'env'         : { 'STARPU_FXT_TRACE' : '1' },
      'opts'        : ['--enable-verbose', '--enable-cuda', '--enable-opencl', '--enable-memory-stats', '--enable-model-debug', '--enable-mpi', '--enable-mpi-check', '--enable-cuda0', '--disable-hip', '--disable-opencl', '--disable-openmp', '--enable-mpi-minimal-tests'],
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'cuda1',
      'env'         : { 'STARPU_FXT_TRACE' : '1' },
      'opts'        : ['--enable-verbose', '--enable-cuda', '--enable-opencl', '--enable-memory-stats', '--enable-model-debug', '--enable-mpi', '--enable-mpi-check', '--enable-cuda1', '--disable-hip', '--disable-opencl', '--disable-openmp', '--enable-mpi-minimal-tests'],
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'full-options',
      'env'         : { 'STARPU_FXT_TRACE' : '1' },
      'opts'        : ['--enable-verbose', '--enable-cuda', '--enable-opencl', '--enable-memory-stats', '--enable-model-debug', '--enable-fxt', '--enable-mpi', '--enable-mpi-check'],
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'full-options-without-fxt',
      'opts'        : ['--enable-verbose', '--enable-cuda', '--enable-opencl', '--enable-memory-stats', '--enable-model-debug', '--disable-fxt'],
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'full-options-and-fxt-poti',
      'env'         : { 'STARPU_FXT_TRACE' : '1' },
      'opts'        : ['--enable-verbose', '--enable-cuda', '--enable-opencl', '--enable-memory-stats', '--enable-model-debug', '--enable-fxt', '--enable-mpi', '--enable-mpi-check', '--enable-poti'],
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'full-options-and-fxt-lock',
      'env'         : { 'STARPU_FXT_TRACE' : '1' },
      'opts'        : ['--enable-verbose', '--enable-cuda', '--enable-opencl', '--enable-memory-stats', '--enable-model-debug', '--enable-fxt', '--enable-mpi', '--enable-mpi-check', '--enable-fxt-lock'],
      'deploy'      : False,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'disable-all',
      'opts'        : ['--disable-cuda', '--disable-hip', '--disable-opencl', '--disable-cpu', '--disable-mpi-check'],
      'deploy'      : True,
      'hosts'       : ['node_nogpu'],
    },
    { 'name'        : 'cuda4-nopeer-transfer',
      'opts'        : ['--disable-hip', '--disable-opencl', '--disable-cpu', '--disable-cuda-memcpy-peer', '--enable-mpi-minimal-tests'],
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'cuda-multiworker',
      'opts'        : ['--enable-mpi-minimal-tests'],
      'env'         : { 'STARPU_NWORKER_PER_CUDA' : '2' },
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'cuda-multithread',
      'opts'        : ['--enable-mpi-minimal-tests'],
      'env'         : { 'STARPU_NWORKER_PER_CUDA' : '2', 'STARPU_CUDA_THREAD_PER_WORKER' : '1' },
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'cuda-monothread',
      'opts'        : ['--enable-mpi-minimal-tests'],
      'env'         : { 'STARPU_CUDA_THREAD_PER_DEV' : '0' },
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'cuda-nopipeline',
      'opts'        : ['--enable-mpi-minimal-tests'],
      'env'         : { 'STARPU_CUDA_PIPELINE' : '0' },
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'opencl-nopipeline',
      'opts'        : ['--enable-mpi-minimal-tests'],
      'env'         : { 'STARPU_NCUDA' : '0', 'STARPU_OPENCL_PIPELINE' : '0' },
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'sched-ctx-hypervisor',
      'opts'        : ['--enable-sc-hypervisor'],
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'starpufft-examples',
      'opts'        : ['--enable-starpufft-examples'],
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'openmp',
      'opts'        : ['--enable-openmp', '--enable-openmp-llvm'],
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'blocking-drivers',
      'opts'        : ['--enable-blocking-drivers'],
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'blocking-drivers-mhp',
      'opts'        : ['--enable-blocking-drivers'],
      'env'         : { 'STARPU_SCHED' : 'modular-heft-prio' },
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'dmdas',
      'env'         : { 'STARPU_SCHED' : 'dmdas' },
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'darts',
      'env'         : { 'STARPU_SCHED' : 'darts' },
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'modular-dmdas',
      'env'         : { 'STARPU_SCHED' : 'modular-dmdas' },
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'graph-test',
      'opts'        : ['--disable-mpi'],
      'env'         : { 'STARPU_SCHED' : 'graph_test' },
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'modular-eager',
      'env'         : { 'STARPU_SCHED' : 'modular-eager' },
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'modular-eager-prio',
      'env'         : { 'STARPU_SCHED' : 'modular-eager-prio' },
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'modular-eager-prefetching',
      'env'         : { 'STARPU_SCHED' : 'modular-eager-prefetching' },
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'modular-ws',
      'env'         : { 'STARPU_SCHED' : 'modular-ws' },
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'modular-heft2',
      'env'         : { 'STARPU_SCHED' : 'modular-heft2' },
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'modular-heft',
      'env'         : { 'STARPU_SCHED' : 'modular-heft' },
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'modular-heft-prio',
      'env'         : { 'STARPU_SCHED' : 'modular-heft-prio' },
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'modular-heteroprio',
      'env'         : { 'STARPU_SCHED' : 'modular-heteroprio' },
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'heteroprio',
      'env'         : { 'STARPU_SCHED' : 'heteroprio' },
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'arbiter',
      'env'         : { 'STARPU_GLOBAL_ARBITER' : '1' },
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'cluster',
      'opts'        : ['--enable-openmp', '--enable-parallel-worker'],
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'simgrid',
      'opts'        : [ '--enable-simgrid', '--disable-cuda', '--disable-hip', '--disable-opencl', '--disable-mpi' ],
      'deploy'      : True,
      'parallel' : 16,
      'hosts'       : ['node_nogpu'],
    },
    { 'name'        : 'simgrid-opencl',
      'opts'        : [ '--enable-simgrid', '--disable-cuda', '--disable-hip', '--disable-opencl', '--disable-mpi' ],
      'deploy'      : True,
      'parallel' : 16,
      'env'         : { 'STARPU_NCUDA' : '0' },
      'hosts'       : ['node_nogpu'],
    },
    { 'name'        : 'simgrid-mpi',
      'opts'        : [ '--enable-simgrid', '--disable-cuda', '--disable-hip', '--disable-opencl', '--enable-mpi', '--enable-mpi-check', '--disable-fxt', '--disable-shared' ],
      'deploy'      : True,
      'parallel' : 16,
      'hosts'       : ['node_nogpu'],
    },
    { 'name'        : 'simgrid-mc',
      'env'         : { 'LD_LIBRARY_PATH' : '/usr/local/stow/simgrid-3.32-mc/lib',
                        # see https://github.com/ROCm/clr/pull/101
                        'HWLOC_COMPONENTS' : '-opencl',
      },
      'opts'        : [ '--enable-simgrid', '--disable-mpi', '--enable-simgrid-mc', '--with-simgrid-dir=/usr/local/stow/simgrid-3.32-mc', '--disable-cuda', '--disable-hip', '--disable-opencl', '--enable-blas-lib=none', '--disable-mlr', '--disable-glpk', '--disable-starpupy' ],
      'deploy'      : True,
      'parallel'    : 16,
      'hosts'       : ['node_nogpu'],
    },
    { 'name'        : 'simgrid-only',
      'env'         : { 'STARPU_FXT_TRACE' : '1' },
      'opts'        : [ '--enable-simgrid', '--disable-mpi', '--disable-cuda', '--disable-hip', '--disable-opencl', '--disable-blas-lib' ],
      'deploy'      : True,
      'hosts'       : ['node_nogpu'],
    },
    { 'name'        : 'simgrid-nogpu',
      'opts'        : [ '--enable-simgrid', '--disable-mpi', '--disable-cuda', '--disable-hip', '--disable-opencl' ],
      'deploy'      : True,
      'parallel'    : 16,
      'hosts'       : ['node_nogpu'],
    },
    { 'name'        : 'starpurm',
      'opts'        : ['--enable-starpurm', '--enable-starpurm-examples'],
      'rcheck'      : ['-C', 'starpurm'],
      'deploy'      : True,
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'julia',
      'opts'        : ['--enable-julia'],
      'deploy'      : True,
      'rcheck'      : ['-C', 'julia'],
      'hosts'       : ['node_gpu']
    },
    { 'name'        : 'starpupy-multi-interp',
      'env'         : { 'STARPUPY_MULTI_INTERPRETER' : '1' },
      'deploy'      : True,
      'hosts'       : ['node_gpu'],
      'rcheck'      : ['-C', 'starpupy']

    },
    { 'name'        : 'starpupy-mpi-ms',
      'opts'        : ['--enable-python-multi-interpreter', '--enable-mpi-server-client', '--disable-socl', '--disable-cpu', '--disable-cuda', '--disable-hip', '--disable-opencl'],
      'deploy'      : True,
      'hosts'       : ['node_nogpu'],
      'rcheck'      : ['-C', 'starpupy']
    },
    { 'name'        : 'starpupy-tcpip-ms',
      'opts'        : ['--enable-python-multi-interpreter', '--enable-tcpip-server-client', '--disable-socl', '--disable-cpu', '--disable-cuda', '--disable-hip', '--disable-opencl', '--disable-starpu-openmp'],
      'deploy'      : True,
      'hosts'       : ['node_nogpu'],
      'rcheck'      : ['-C', 'starpupy']
    },

    { 'name'        : 'intel-mpi',
      'opts'        : ['--with-mpicc=/soft/amd64/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/bin/mpicc', '--with-mpirun=/soft/amd64/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/bin/mpirun', '--disable-fortran'],
      'deploy'      : True,
      'hosts'       : ['node_gpu'],
    },

    # Intel profile
    { 'name'        : 'intel',
      'opts'        : ['--disable-cuda', '--disable-opencl', '--disable-hip', '--disable-static', '--disable-starpupy', '--enable-blas-lib=none'],
      'env'         : { 'CC' : 'icx -fpie', 'CXX' : 'icpx', 'FCC' : 'ifx', 'F77' : 'ifx', 'FC' : 'ifx', 'OMPI_CC' : 'icpx', 'LDSHARED' : 'icpx', 'LD_LIBRARY_PATH' : '/soft/amd64/intel/compilers_and_libraries/linux/lib/intel64_lin'},
      'deploy'      : True,
      'prologue'    : [".", "/soft/amd64/intel/oneapi/2025.0/oneapi-vars.sh", "--force"],
      'hosts'       : ['node_gpu'],
    },

    # Valgrind profiles
    { 'name'        : 'valgrind-tcp-ip',
      'opts'        : ['--disable-verbose', '--disable-cuda', '--disable-hip', '--disable-opencl', '--enable-tcpip-server-client',
                       '--enable-memory-stats', '--enable-model-debug', '--enable-quick-check', '--enable-maxcpus=2', '--enable-maxnumanodes=8',
                       '--enable-mpi-pedantic-isend', '--enable-mpi-check', '--enable-openmp', '--with-mpiexec=mpiexec-nobind', '--disable-full-gdb-information', '--disable-starpu-openmp'],
      'global_env'  : False,
      'env'         : { 'LDFLAGS' : '-no-pie',
                        'STARPU_CHECK_LAUNCHER' : '$starpu_src_dir/tools/dev/valgrind/valgrind.sh',
                        'STARPU_WORKERS_NOBIND' : '1',
                        'NMAD_NUIOA_DISABLE' : '1',
                        'PIOM_DEDICATED_NOBIND' : '1',
                        'LD_PRELOAD' : '/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so:/usr/lib/x86_64-linux-gnu/valgrind/libmpiwrap-amd64-linux.so',
                        'MALLOC_PERTURB_' : '1234',
                        'OPENBLAS_NUM_THREADS': '1',
                        'STARPU_PROFILING' : '1',
                        'STARPU_USE_NUMA' : '1',
                        'STARPU_WORKERS_CPUID' : '0 8',
                        'PYTHONMALLOC' : 'malloc'
                       },
      'deploy'      : True,
      'parallel'    : '10',
      'hosts'       : ['node_nogpu'],
    },
    { 'name'        : 'helgrind',
      'opts'        : ['--enable-spinlock-check', '--disable-verbose', '--enable-tcpip-server-client',
                       '--disable-cuda', '--disable-hip', '--disable-opencl', '--enable-memory-stats', '--enable-model-debug',
                       '--enable-quick-check', '--enable-maxcpus=2', '--enable-maxnumanodes=8', '--enable-mpi-check', '--enable-openmp',
                       '--enable-mpi-pedantic-isend', '--with-mpiexec=mpiexec-nobind', '--disable-full-gdb-information', '--disable-starpu-openmp'],
      'global_env'  : False,
      'env'         : { 'LDFLAGS' : '-no-pie',
                        'STARPU_CHECK_LAUNCHER' : '$starpu_src_dir/tools/dev/valgrind/helgrind.sh',
                        'STARPU_WORKERS_NOBIND' : '1',
                        'NMAD_NUIOA_DISABLE' : '1',
                        'PIOM_DEDICATED_NOBIND' : '1',
                        'MALLOC_PERTURB_' : '1234',
                        'OPENBLAS_NUM_THREADS': '1',
                        'STARPU_PROFILING' : '1',
                        'STARPU_USE_NUMA' : '1',
                        'STARPU_WORKERS_CPUID' : '0 8',
                        'PYTHONMALLOC' : 'malloc'
                       },
      'deploy'      : True,
      'parallel'    : '10',
      'hosts'       : ['node_nogpu'],
    },
    { 'name'        : 'tsan',
      'opts'        : ['--enable-spinlock-check', '--enable-verbose', '--enable-tcpip-server-client',
                       '--disable-cuda', '--disable-hip', '--disable-opencl', '--enable-memory-stats', '--enable-model-debug',
                       '--enable-maxcpus=8', '--enable-maxnumanodes=8', '--enable-openmp', '--disable-full-gdb-information', '--disable-starpu-openmp'],
      'global_env'  : False,
      'env'         : { 'ac_cv_prog_ICC': '', 'ac_cv_path_ICC': '',
                        'FFLAGS' : '-fsanitize=thread -fPIC -DSTARPU_SANITIZE_THREAD',
                        'FCFLAGS' : '-fsanitize=thread -fPIC -DSTARPU_SANITIZE_THREAD',
                        'CFLAGS' : '-fsanitize=thread -fPIC -DSTARPU_SANITIZE_THREAD',
                        'CXXFLAGS' : '-fsanitize=thread -fPIC -DSTARPU_SANITIZE_THREAD',
                        'LDFLAGS' : '-fsanitize=thread',
                        'STARPU_WORKERS_NOBIND' : '1',
                        'NMAD_NUIOA_DISABLE' : '1',
                        'PIOM_DEDICATED_NOBIND' : '1',
                        'TSAN_OPTIONS' : 'suppressions=$starpu_src_dir/tools/dev/tsan/starpu.suppr exitcode=42',
                        'GLIBC_TUNABLES' : 'glibc.rtld.optional_static_tls=1048576',
                        'MALLOC_PERTURB_' : '1234',
                        'OPENBLAS_NUM_THREADS': '1',
                        'STARPU_PROFILING' : '1', 'STARPU_PROF_PAPI_EVENTS' : 'PAPI_TOT_INS PAPI_TOT_CYC',
                        'STARPU_USE_NUMA' : '1',
                        'STARPU_WORKERS_CPUID' : '0 2 8 9 16 17 24 25',
                       },
      'deploy'      : True,
      'parallel'    : '10',
      'hosts'       : ['node_nogpu'],
    },
    { 'name'        : 'asan',
      'opts'        : ['--enable-spinlock-check', '--enable-verbose', '--enable-tcpip-server-client',
                       '--disable-cuda', '--disable-hip', '--disable-opencl', '--enable-memory-stats', '--enable-model-debug',
                       '--enable-maxcpus=128', '--enable-maxnumanodes=8', '--enable-openmp', '--disable-full-gdb-information', '--disable-starpu-openmp'],
      'global_env'  : False,
      'env'         : { 'ac_cv_prog_ICC': '', 'ac_cv_path_ICC': '',
                        'FFLAGS' : '-fsanitize=address -fPIC -DSTARPU_SANITIZE_ADDRESS',
                        'FCFLAGS' : '-fsanitize=address -fPIC -DSTARPU_SANITIZE_ADDRESS',
                        'CFLAGS' : '-fsanitize=address -fPIC -DSTARPU_SANITIZE_ADDRESS',
                        'CXXFLAGS' : '-fsanitize=address -fPIC -DSTARPU_SANITIZE_ADDRESS',
                        'LDFLAGS' : '-fsanitize=address -pie',
                        'STARPU_WORKERS_NOBIND' : '1',
                        'NMAD_NUIOA_DISABLE' : '1',
                        'PIOM_DEDICATED_NOBIND' : '1',
                        'ASAN_OPTIONS' : 'exitcode=42 detect_leaks=0',
                        'MALLOC_PERTURB_' : '1234',
                        'OPENBLAS_NUM_THREADS': '1',
                        'STARPU_LD_PRELOAD' : 'libasan.so.8',
                        'STARPU_PROFILING' : '1', 'STARPU_PROF_PAPI_EVENTS' : 'PAPI_TOT_INS PAPI_TOT_CYC',
                        'STARPU_USE_NUMA' : '1',
                       },
      'deploy'      : True,
      'parallel'    : '10',
      'hosts'       : ['node_nogpu'],
      },
    # if you need to stop on an ubsan report via a breakpoint with gdb, do the following in gdb
    # b __ubsan::ScopedReport::~ScopedReport
    # b __ubsan::Diag::~Diag
    { 'name'        : 'usan',
      'opts'        : ['--enable-spinlock-check', '--enable-verbose', '--enable-tcpip-server-client',
                       '--disable-cuda', '--disable-hip', '--disable-opencl', '--enable-memory-stats', '--enable-model-debug',
                       '--enable-maxcpus=128', '--enable-maxnumanodes=8', '--enable-mpi-check', '--enable-openmp', '--with-mpiexec=mpiexec-nobind', '--disable-full-gdb-information', '--disable-starpu-openmp'],
      'global_env'  : False,
      'env'         : { 'ac_cv_prog_ICC': '', 'ac_cv_path_ICC': '',
                        'FFLAGS' : '-fsanitize=undefined -DSTARPU_SANITIZE_UNDEFINED',
                        'FCFLAGS' : '-fsanitize=undefined -DSTARPU_SANITIZE_UNDEFINED',
                        'CFLAGS' : '-fsanitize=undefined -DSTARPU_SANITIZE_UNDEFINED',
                        'CXXFLAGS' : '-fsanitize=undefined -DSTARPU_SANITIZE_UNDEFINED',
                        'LDFLAGS' : '-fsanitize=undefined -DSTARPU_SANITIZE_UNDEFINED',
                        'STARPU_WORKERS_NOBIND' : '1',
                        'NMAD_NUIOA_DISABLE' : '1',
                        'PIOM_DEDICATED_NOBIND' : '1',
                        'UBSAN_OPTIONS' : 'halt_on_error=1:exitcode=42',
                        'MALLOC_PERTURB_' : '1234',
                        'OPENBLAS_NUM_THREADS': '1',
                        'STARPU_PROFILING' : '1', 'STARPU_PROF_PAPI_EVENTS' : 'PAPI_TOT_INS PAPI_TOT_CYC',
                        'STARPU_USE_NUMA' : '1',
                       },
      'deploy'      : True,
      'parallel'    : '10',
      'hosts'       : ['node_nogpu'],
    },
    { 'name'        : 'lsan',
      'opts'        : ['--enable-spinlock-check', '--enable-verbose', '--enable-tcpip-server-client',
                       '--disable-cuda', '--disable-hip', '--disable-opencl', '--enable-memory-stats', '--enable-model-debug',
                       '--enable-maxcpus=128', '--enable-maxnumanodes=8', '--enable-openmp', '--disable-full-gdb-information', '--disable-mpi-check', '--disable-starpu-openmp'],
      'global_env'  : False,
      'hwloc_input' : False,
      'env'         : { 'ac_cv_prog_ICC': '', 'ac_cv_path_ICC': '',
                        'FFLAGS' : '-fsanitize=address -fPIC -DSTARPU_SANITIZE_ADDRESS -DSTARPU_SANITIZE_LEAK',
                        'FCFLAGS' : '-fsanitize=address -fPIC -DSTARPU_SANITIZE_ADDRESS -DSTARPU_SANITIZE_LEAK',
                        'CFLAGS' : '-fsanitize=address -fPIC -DSTARPU_SANITIZE_ADDRESS -DSTARPU_SANITIZE_LEAK',
                        'CXXFLAGS' : '-fsanitize=address -fPIC -DSTARPU_SANITIZE_ADDRESS -DSTARPU_SANITIZE_LEAK',
                        'LDFLAGS' : '-fsanitize=address -pie',
                        'STARPU_WORKERS_NOBIND' : '1',
                        'NMAD_NUIOA_DISABLE' : '1',
                        'PIOM_DEDICATED_NOBIND' : '1',
                        'ASAN_OPTIONS' : 'fast_unwind_on_malloc=0',
                        'LSAN_OPTIONS' : 'suppressions=$starpu_src_dir/tools/dev/lsan/suppressions exitcode=42 malloc_context_size=24 verbosity=1',
                        'MALLOC_PERTURB_' : '1234',
                        'OPENBLAS_NUM_THREADS': '1',
                        'STARPU_LD_PRELOAD' : 'libasan.so.8',
                        'STARPU_HWLOC_INPUT': '',
                        'STARPU_PROFILING' : '1', 'STARPU_PROF_PAPI_EVENTS' : 'PAPI_TOT_INS PAPI_TOT_CYC',
                        'STARPU_USE_NUMA' : '1',
                        'PYTHONMALLOC' : 'malloc'
                       },
      'deploy'      : True,
      'parallel'    : '10',
      'hosts'       : ['node_nogpu'],
      'showsuite'   : False
    },

    # valgrind profile
    { 'name'        : 'valgrind',
      'opts'        : ['--disable-verbose', '--disable-cuda', '--disable-hip', '--disable-opencl', '--enable-starpurm', '--enable-starpurm-examples',
                       '--enable-memory-stats', '--enable-model-debug', '--enable-quick-check', '--enable-maxcpus=2', '--enable-maxnumanodes=8',
                       '--enable-mpi-pedantic-isend', '--enable-mpi-check', '--enable-openmp', '--with-mpiexec=mpiexec-nobind', '--disable-starpu-top',
                       '--enable-coverage'],
      #, '--with-check-flags="-fanalyzer"'],
      'global_env' : False,
      'env'         : { 'LDFLAGS' : '-no-pie',
                        'STARPU_CHECK_LAUNCHER' : '$starpu_src_dir/tools/dev/valgrind/valgrind_xml.sh',
                        'STARPU_WORKERS_NOBIND' : '1',
                        'NMAD_NUIOA_DISABLE' : '1',
                        'PIOM_DEDICATED_NOBIND' : '1',
                        'LD_PRELOAD' : '/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so:/usr/lib/x86_64-linux-gnu/valgrind/libmpiwrap-amd64-linux.so',
                        'MALLOC_PERTURB_' : '1234',
                        'OPENBLAS_NUM_THREADS': '1',
                        'STARPU_PROFILING' : '1',
                        'STARPU_USE_NUMA' : '1',
                        'STARPU_WORKERS_CPUID' : '0 8',
                        'PYTHONMALLOC' : 'malloc'
                       },
      'deploy'      : True,
      'ignore_check_errors' : True,
      'parallel'    : '10',
      'hosts'       : ['node_nogpu'],
    },

    # NVIDIA compute-sanitizer profiles
    { 'name'        : 'compute-sanitizer',
      'opts'        : ['--disable-verbose', '--disable-hip', '--disable-opencl', '--enable-starpurm', '--enable-starpurm-examples',
                       '--enable-memory-stats', '--enable-model-debug', '--enable-quick-check', '--enable-maxcpus=2', '--enable-maxnumanodes=8'],
      'env'         : { 'STARPU_CHECK_LAUNCHER' : 'compute-sanitizer --require-cuda-init=no --error-exitcode=1',
                        'STARPU_PROFILING' : '1',
                        'STARPU_USE_NUMA' : '1',
                       },
      'deploy'      : True,
      'hosts'       : ['node_gpu'],
    },
    { 'name'        : 'compute-sanitizer-race',
      'opts'        : ['--disable-verbose', '--disable-hip', '--disable-opencl', '--enable-starpurm', '--enable-starpurm-examples',
                       '--enable-memory-stats', '--enable-model-debug', '--enable-quick-check', '--enable-maxcpus=2', '--enable-maxnumanodes=8'],
      'env'         : { 'STARPU_CHECK_LAUNCHER' : 'compute-sanitizer --require-cuda-init=no --error-exitcode=1 --tool racecheck',
                        'STARPU_PROFILING' : '1',
                        'STARPU_USE_NUMA' : '1',
                       },
      'deploy'      : True,
      'hosts'       : ['node_gpu'],
    },
    { 'name'        : 'compute-sanitizer-sync',
      'opts'        : ['--disable-verbose', '--disable-hip', '--disable-opencl', '--enable-starpurm', '--enable-starpurm-examples',
                       '--enable-memory-stats', '--enable-model-debug', '--enable-quick-check', '--enable-maxcpus=2', '--enable-maxnumanodes=8'],
      'env'         : { 'STARPU_CHECK_LAUNCHER' : 'compute-sanitizer --require-cuda-init=no --error-exitcode=1 --tool synccheck',
                        'STARPU_PROFILING' : '1',
                        'STARPU_USE_NUMA' : '1',
                       },
      'deploy'      : True,
      'hosts'       : ['node_gpu'],
    },
    # dalton32 profile
    { 'name'        : '32bit',
      'opts'        : ['--disable-fxt'],
      'deploy'      : True,
      'hosts'       : ['node_32bit'],
    },

]

####  # Build configuration
####
####  # Execution configuration
####  STARPU_NCUDA=0
####  # Execution configuration
####  STARPU_NCUDA=1
####  # Execution configuration
####  STARPU_SCHED=ws
####  # Execution configuration
####  STARPU_SCHED=prio
####  # Execution configuration
####  STARPU_SCHED=no-prio
####  # Execution configuration
####  STARPU_SCHED=dm
####  # Execution configuration
####  STARPU_SCHED=dmda
####  # Execution configuration
####  STARPU_SCHED=random
####  # Execution configuration
####  STARPU_SCHED=eager
####  # Execution configuration
####  STARPU_SCHED=dmda STARPU_SCHED_ALPHA=10 STARPU_SCHED_BETA=15
####  # Execution configuration
####  STARPU_CALIBRATE=1
####  # Execution configuration
####  STARPU_PREFETCH=1
####
