#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>

#include <common/fxt.h>

fxt_t fut;
struct fxt_ev_64 ev;

void handle_new_worker(void)
{

	char *str = "unknown";

	switch (ev.param[0]) {
		case FUT_APPS_KEY:
			str = "apps";
			break;
		case FUT_CORE_KEY:
			str = "core";
			break;
		case FUT_CUDA_KEY:
			str = "cuda";
			break;
		case FUT_CUBLAS_KEY:
			str = "cublas";
			break;
	}

	printf("new %s worker (tid = %d)\n", str, ev.param[1]);
}

void handle_start_codelet_body(void)
{
	printf("start codelet %p on tid %d\n", ev.param[0], ev.param[1]);
}

void handle_end_codelet_body(void)
{
	printf("end codelet %p on tid %d\n", ev.param[0], ev.param[1]);
}

/*
 * This program should be used to parse the log generated by FxT 
 */
int main(int argc, char **argv)
{
	char *filename;
	int ret;
	int fd;
	
	if (argc != 2) {
	        printf("Usage : %s filename\n", argv[0]);
	        exit(-1);
	}
	
	filename = argv[1];
	
	fd = open(filename, O_RDONLY);
	if (fd < 0) {
	        perror("open failed :");
	        exit(-1);
	}
	
	fut = fxt_fdopen(fd);
	if (!fut) {
	        perror("fxt_fdopen :");
	        exit(-1);
	}
	
	fxt_blockev_t block;
	block = fxt_blockev_enter(fut);

	while(1) {
		ret = fxt_next_ev(block, FXT_EV_TYPE_64, (struct fxt_ev *)&ev);
		if (ret != FXT_EV_OK) {
			printf("no more block ...\n");
			break;
		}

		int nbparam = ev.nb_params;

		switch (ev.code) {
			case FUT_NEW_WORKER_KEY:
				handle_new_worker();
				break;
			case FUT_START_CODELET_BODY:
				handle_start_codelet_body();
				break;
			case FUT_END_CODELET_BODY:
				handle_end_codelet_body();
				break;
			default:
				printf("event.. %x at time %llx\n", ev.code, ev.time);
				break;
		}
	}

	return 0;
}
