for ((i=1 ; i<=20; i++))
do
	# N=50 ; BLOCK=3840 ; STARPU_SCHED=dmdar STARPU_MINIMUM_CLEAN_BUFFERS=0 STARPU_CALIBRATE_MINIMUM=40 STARPU_TARGET_CLEAN_BUFFERS=0 STARPU_NCPU=0 STARPU_NCUDA=8 STARPU_CALIBRATE=1 STARPU_NOPENCL=0 ./examples/cholesky/cholesky_implicit -size $((BLOCK*N)) -nblocks $((N))

	N=30 ; BLOCK=1920 ; STARPU_SCHED=dmdar STARPU_MINIMUM_CLEAN_BUFFERS=0 STARPU_CALIBRATE_MINIMUM=50 STARPU_TARGET_CLEAN_BUFFERS=0 STARPU_NCPU=0 STARPU_NCUDA=8 STARPU_CALIBRATE=1 STARPU_NOPENCL=0 ./examples/lu/lu_implicit_example_double -size $((BLOCK*N)) -nblocks $((N))
done
