#!/bin/bash
[ -z "$N" ] && N=1
export N
[ -z "$STARPU_SCHED_BETA" ] && STARPU_SCHED_BETA="2"
export STARPU_SCHED_BETA
echo sched $STARPU_SCHED 1>&2
echo sched_beta $STARPU_SCHED_BETA 1>&2
echo prefetch $STARPU_PREFETCH 1>&2
echo calibrate $STARPU_CALIBRATE 1>&2
echo ncpus $STARPU_NCPUS 1>&2
echo ncuda $STARPU_NCUDA 1>&2
echo N $N
./stencil -nbz $(($N * 64)) -sizex 128 -sizey 128 -sizez $(( $((16 * $N)) * 128 )) -niter 64 "$@"
