all:
#~ 	buf_size=999999 pdflatex Data_coordinates.tex
#~ 	buf_size=999999 pdflatex Data_coordinates_order.tex
#~ 	buf_size=999999 pdflatex Data_coordinates_order_last.tex
	buf_size=999999 pdflatex Data_coordinates_order_last_SCHEDULER.tex
	buf_size=999999 pdflatex Data_coordinates_order_last_HEFT.tex
	buf_size=999999 pdflatex Data_coordinates_order_last_HFP.tex
	buf_size=999999 pdflatex Data_coordinates_order_last_hMETIS.tex
	buf_size=999999 pdflatex Data_in_gpu_HFP.tex
	buf_size=999999 pdflatex visualisation_matrice_2D.tex
#~ 	rm -f Data_coordinates_order.log Data_coordinates_order.aux
#~ 	rm -f Data_coordinates_order_last.log Data_coordinates_order_last.aux
	rm -f Data_coordinates_order_last_HEFT.log Data_coordinates_order_last_HEFT.aux
	rm -f Data_coordinates_order_last_HEFT.log Data_coordinates_order_last_SCHEDULER.aux
	rm -f Data_coordinates_order_last_HFP.log Data_coordinates_order_last_HFP.aux
	rm -f Data_coordinates_order_last_HFP.log Data_coordinates_order_last_hMETIS.aux
	rm -f Data_in_gpu_HFP.log Data_in_gpu_HFP.aux
#~ 	rm -f Data_coordinates.log Data_coordinates.aux
