all:
	buf_size=999999 pdflatex Data_coordinates.tex
	buf_size=999999 pdflatex Data_coordinates_order.tex
	buf_size=999999 pdflatex Data_coordinates_order_last.tex
	rm -f Data_coordinates_order.log Data_coordinates_order.aux
	rm -f Data_coordinates_order_last.log Data_coordinates_order_last.aux
	rm -f Data_coordinates.log Data_coordinates.aux
