# StarPU --- Resource Management Layer.
#
# Copyright (C) 2017, 2018                               Inria
#
# StarPU is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or (at
# your option) any later version.
#
# StarPU is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU Lesser General Public License in COPYING.LGPL for more details.

PRG=dgemm

CC=icc
CFLAGS=-Wall -g -O2
LDLIBS=

CFLAGS+=$(shell pkg-config --static --cflags chameleon) -I/home/aumage/Git/Chameleon/install/include/libhqr
LDLIBS+=$(shell pkg-config --static --libs chameleon)

CFLAGS+=$(shell pkg-config --cflags starpurm-1.3)
LDLIBS += $(shell pkg-config --libs starpurm-1.3)

.phony: all clean
all: $(PRG)
clean:
	rm -f $(PRG) *.o
