#export STARPU_GENERATE_TRACE=1
#export GOMP_CPU_AFFINITY="0 6 1 7 2 8 3 9 4 10 5 11"
#export OMP_WAIT_POLICY=PASSIVE
export STARPU_SCHED=pheft
export STARPU_NCPUS=12
export STARPU_SINGLE_COMBINED_WORKER=1
export STARPU_MIN_WORKERSIZE=12
export STARPU_MAX_WORKERSIZE=12
export STARPU_NCUDA=0
export STARPU_NOPENCL=0
export STARPU_WORKER_STATS=1
export STARPU_CALIBRATE=1
./bfs data/graph65536.txt
