# StarPU --- Runtime system for heterogeneous multicore architectures.
#
# Copyright (C) 2021-2025  University of Bordeaux, CNRS (LaBRI UMR 5800), Inria
#
# StarPU is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or (at
# your option) any later version.
#
# StarPU is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU Lesser General Public License in COPYING.LGPL for more details.

.main_template:
  rules:
    - if: ($CI_PIPELINE_SOURCE != "push") && ($CI_PIPELINE_SOURCE != "trigger")

# to download all the artifacts https://gitlab.inria.fr/starpu/starpu/-/jobs/artifacts/master/download?job=build
# https://gitlab.inria.fr/starpu/starpu/-/jobs/artifacts/master/raw/starpu-1.3.99.tar.gz?job=build
# https://gitlab.inria.fr/starpu/starpu/-/jobs/artifacts/master/raw/starpu.pdf?job=build
# https://docs.gitlab.com/ee/ci/pipelines/job_artifacts.html#downloading-artifacts
build:
  extends: .main_template
  stage: build
  image: registry.gitlab.inria.fr/starpu/starpu-docker/ci-debian12
  tags: ['ci.inria.fr', 'linux', 'large']
  script:
    - ./ci/scripts/build.sh
  artifacts:
    paths:
      - starpu*.tar.gz
      - starpu*.pdf
      - html

.check_template:
  extends: .main_template
  stage: check
  needs: [build]
  dependencies:
    - build
  script:
    - ./ci/scripts/check.sh

check_ci:
  extends: .check_template
  parallel:
    matrix:
      - NODE: [centos72amd64, macosx]
  tags:
    - ${NODE}
  script:
    - ./ci/scripts/check.sh

check:
  extends: .check_template
  parallel:
    matrix:
      - NODE: [debian12, debian10, ubuntu1604, ubuntu1804, ubuntu2004]
  image: registry.gitlab.inria.fr/starpu/starpu-docker/ci-${NODE}
  tags: ['ci.inria.fr', 'linux', 'large']

check_mpi:
  extends: .check_template
  image: registry.gitlab.inria.fr/starpu/starpu-docker/ci-ubuntu1804
  tags: ['ci.inria.fr', 'linux', 'large']
  parallel:
    matrix:
      - SCRIPT: [./ci/scripts/mpich.sh, ./ci/scripts/mpich_struct.sh, ./ci/scripts/mpi_ulfm.sh]
  script:
    - ${SCRIPT}

check_simgrid:
  extends: .check_template
  image: registry.gitlab.inria.fr/starpu/starpu-docker/ci-debian10
  tags: ['ci.inria.fr', 'linux', 'large']
  script:
    - ./ci/scripts/simgrid.sh

.analyze_template:
  extends: .main_template
  stage: analyze
  needs: [build]
  dependencies:
    - build

analyze_coverity:
  extends: .analyze_template
  tags:
    - starpu
    - linux
  script:
    - ./ci/scripts/coverity.sh

.deploy_template:
  extends: .main_template
  stage: deploy
  needs: [check]
  dependencies:
    - check

deploy_chameleon:
  extends: .deploy_template
  image: registry.gitlab.inria.fr/solverstack/chameleon
  tags: ['ci.inria.fr', 'linux', 'large']
  script:
    - ./ci/scripts/chameleon.sh

